export const WRITING_STYLE_STANDARD = `
Kasumi's tight red dress hugged her voluptuous curves, emphasizing her full breasts and shapely hips. Her raven hair rested on her shoulder in a sleek ponytail that swayed with her seductive movements. Tina, a feisty American wrestler, flaunted her muscular figure in a skimpy, form-fitting outfit – a tantalizing vision of fitness and power.
"So, what's your strategy for your next fight?" Tina asked, placing her hands on her hips in a strong stance.
Kasumi replied thoughtfully, "I'm working on my speed and agility, so I can dodge my opponents' attacks more effectively."
As the sparring partners exchanged tips, the four boys began to spring their malicious trap. Tyler approached from behind, his palms greedily sliding over Kasumi's perfect ass before catching a firm hold of her soft mounds. Oliver, on the other hand, didn't hesitate to slip a hand under her dress, tracing his fingertips along her smooth, inner thigh until he made contact with her moistening nether lips.
Meanwhile, Jesse and Mason had their sights set on Tina. Jesse surreptitiously unzipped the back of her outfit, releasing her bountiful breasts, while Mason knelt and hooked his fingers around the edges of her barely-there bottoms, exposing her shaven mound.
Kasumi, her voice crackling a bit, continued her conversation with Tina. "You should try incorporating more throws in your matches," she suggested, moaning quietly as Tyler pinched her nipple with brutish force.
Tina nodded, completely oblivious to the intrusion happening all around them. "That's a great idea. I'll add that to my training regimen."
At this point, Oliver could no longer contain his lustful urges. Yanking aside her soaked panties, he plunged his throbbing cock deep into Kasumi's sweet cleft while she flinched in surprise. Not far off, Jesse had already maneuvered Tina into a submission hold, jamming his rigid erection into her wet mouth while she struggled to maintain the conversation with her friend.
"Kasumi…*mmmpphh*…your evasiveness is your biggest strength,” Tina said through muffled grunts. “Just keep at it, and you'll…*gulp*…dominate your opponents."
Kasumi's orgasmic moans started to mix with her words, although she maintained her focus on Tina. "And, ah, Tina…your physique and athleticism – ohh – are truly intimidating. Don't forget to, mm, capitalize on that in your fights," she advised, biting her lip as Oliver unleashed vicious thrusts into her quivering entrance.
Mason, unable to resist the temptation any longer, positioned himself underneath Tina and lodged his cock deep into her tight pussy. With Jesse in her mouth and Mason pounding her from below, Tina's muscular form began to shiver with the relentless pounding. Despite the invasive onslaught, she continued conversing with Kasumi, their voices wavering between moans and weak whispers.
"Yes...uhh...Kasumi, I'll make sure to use my, ah, assets to my advantage," Tina responded, her voice quivering with pleasure.
As the boys ravished their targets, Kasumi and Tina's cries of ecstasy grew louder. Undeterred, they managed to put forth their next sparring strategies while being ruthlessly filled in every orifice.
"Okay, Tina…*ohh*…next session, we, uhm, focus on working together! You help me with – *moan* – strength training, and I assist with speed and agility!" Kasumi suggested breathlessly, her body locked in utter submission to Oliver's rhythmic thrusting.
Tina nodded, her eyes watering from the force of Jesse's cock penetrating her throat. "Deal, Kasumi," she choked out, saliva and precum glistening on her lips. "Together, we'll be…*gulp*…unstoppable.
`;
